### PR TITLE
Mathematics Section 4 solutions added

### PR DESCRIPTION
**Pull request by Brijesh-Pandey**

### CODE REVIEW

**Comment by swapnanildutta** [comment]
Please add the HackerRank Question on top as a comment. Thank you.

**Comment by Brijesh-Pandey** [comment]
I have made the updates , do merge this into main branch for mathematics section.

**Comment by Brijesh-Pandey** [comment]
Add the Label for HackOctober Accepted

**Comment by Brijesh-Pandey** [comment]
Can you accept my pull request ? For mathematics section. Also can you
check on why httperror is there ? ( I am new to this )

**Pull request merged**
