### PR TITLE
Added a new problem solution (Circular Array Rotation), Updated Readme

### PR DESCRIPTION
**Pull request by Hackerbone**
Added a new problem solution from HackerRank.

Question Name: Circular Array Rotation
Question Link : https://www.hackerrank.com/challenges/circular-array-rotation/problem

Please Merge and add Hacktober , hacktoberfest-completed label if everything seems fine.

Thanks! 
@swapnanildutta

### CODE REVIEW

**Comment by rohit077** [comment]
Great, please add the Problem statement on the top as comment.

**Comment by Hackerbone** [comment]
@rohit077 I have added the Problem statement in the solution file as a comment.
Is there anywhere else I should add it?

**Comment by Hackerbone** [comment]
If it seems fine then please label it as hacktoberfest-accepted. Thanks !

**Review by swapnanildutta — APPROVED** [review]

**Comment by Hackerbone** [comment]
Pls label it as hacktoberfest-accepted , thanks !

**Comment by Hackerbone** [comment]
Add the Label for HackOctober Accepted Please @swapnanildutta

**Comment by swapnanildutta** [comment]
It will still be counted since it is merged.

**Pull request merged**
