### PR TITLE
Added Scala directory with one problem

### PR DESCRIPTION
**Pull request by thepurpleowl**

### CODE REVIEW

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the question on top as a comment, and if you solved the **Problem Solving** section with scala, then add a **Scala** folder in the Problem Solving directory and add your code with the question.

**Comment by thepurpleowl** [comment]
@swapnanildutta Done.

**Comment by swapnanildutta** [comment]
Scala wasn.t a track in HackerRank. Is this a part of the Problem Solving part?

**Comment by thepurpleowl** [comment]
It's part of problem solving part.

**Comment by swapnanildutta** [comment]
Add the full question as a comment.

**Pull request closed without merging**
