### PR TITLE
added kotlin

### PR DESCRIPTION
**Pull request by sunny52525**
added 30 days of code in kotlin

### CODE REVIEW

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add all your codes with the entire question as a comment on the top of every code, not just links.

**Comment by sunny52525** [comment]
> Please add all your codes with the entire question as a comment on the top of every code, not just links.

Added the questions in the form of comments
and the days which are missing don't have kotlin as an option in the compiler list.

**Comment by swapnanildutta** [comment]
That's okay. Also, add a README. That would be great.

**Comment by sunny52525** [comment]
> That's okay. Also, add a README. That would be great.

Added.

**Review by swapnanildutta — APPROVED** [review]

**Review by swapnanildutta — APPROVED** [review]

**Pull request merged**
