### PR TITLE
Lily's Homework Problem from Hackerrank added

### PR DESCRIPTION
**Pull request by DebadityaPal**
Relevant Issue #9 . Could not find a better issue for the problem-solving subsection.

### CODE REVIEW

**Comment by DebadityaPal** [comment]
Hi, it looks like I am running into some check failures. Could you tell me what I need to do in order to resolve these issues?

**Comment by swapnanildutta** [comment]
> 
> 
> Hi, it looks like I am running into some check failures. Could you tell me what I need to do in order to resolve these issues?

That's not an issue.

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Comment by DebadityaPal** [comment]
The required changes have been made. The question has been added.

**Review by swapnanildutta — APPROVED** [review]

**Pull request merged**
