### PR TITLE
Create QuickSort.py

### PR DESCRIPTION
**Pull request by vivekgsheth**
Added code for QuickSort Algorithm in Python.

### CODE REVIEW

**Comment by vivekgsheth** [comment]
Hi @swapnanildutta  , the code is working fine . I have tested it. Please approve the PR.

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Comment by vivekgsheth** [comment]
Hi @swapnanildutta  , I have added the question link. Please approve the PR.

**Comment by swapnanildutta** [comment]
Not just the Link, the entire question is required as a comment.

**Pull request closed without merging**
