### PR TITLE
code added to python and algorithms

### PR DESCRIPTION
**Pull request by dikshajoshi18**
python changes:
1. Sales by match (EASY)
2. write a function (medium)

algorithms:
Intro to Tutorial Challenges
Marc's Cakewalk
Minimum Absolute Difference in an Array
Permuting Two Arrays

### CODE REVIEW

**Comment by dikshajoshi18** [comment]
python changes:

Sales by match (EASY)
write a function (medium)
algorithms:
Intro to Tutorial Challenges
Marc's Cakewalk
Minimum Absolute Difference in an Array
Permuting Two Arrays

**Comment by dikshajoshi18** [comment]
how to pass the labeler

**Comment by dikshajoshi18** [comment]
what are the standards, sir?
I have added questions, question link, solution what more can I do?
please elaborate.

**Comment by dikshajoshi18** [comment]
I have resolved the issues. please see to it.

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Review by swapnanildutta — APPROVED** [review]

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Add the imports.

**Review by swapnanildutta — APPROVED** [review]

**Comment by swapnanildutta** [comment]
Please change the requested features and I'll merge it.

**Comment by dikshajoshi18** [comment]
done

**Pull request merged**
