### PR TITLE
📝Update Python Readme (Fix #172 ) And Added new Python Solution eval_py

### LINKED ISSUE #172: 🐛 Python Readme : Index Broken
see mutation bullet point in Python Readme.

### PR DESCRIPTION
**Pull request by ashishpawar517**
Let me know what you think about this guys.

### CODE REVIEW

**Comment by swapnanildutta** [comment]
Please add the entire question on top as a comment. Check the other codes in the repository for reference.

**Comment by ashishpawar517** [comment]
Check it out now!

**Comment by swapnanildutta** [comment]
Add the full question from [Link](https://www.hackerrank.com/challenges/python-eval/problem). Check the other codes in the repository for reference.

**Comment by ashishpawar517** [comment]
I have added objective, task, input, output as specified in the problem.

**Pull request closed without merging**
