### PR TITLE
Dynamic Array Solution(Java)

### PR DESCRIPTION
**Pull request by PrinceKhatick**

### CODE REVIEW

**Comment by PrinceKhatick** [comment]
@swapnanildutta  Please check it

**Review by swapnanildutta — APPROVED** [review]

**Comment by PrinceKhatick** [comment]
@swapnanildutta  Please assign the hacktober2020 label for my contribution

**Comment by swapnanildutta** [comment]
It is the same as being merged.

**Comment by PrinceKhatick** [comment]
> It is the same as being merged.

Ok i just saw that

**Pull request merged**
