### PR TITLE
code added to python and algorithms

### PR DESCRIPTION
**Pull request by dikshajoshi18**

### CODE REVIEW

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as a comment. Thank you.

**Comment by dikshajoshi18** [comment]
> Please add the HackerRank Question on top as a comment. Thank you.

sir I have added already

**Review by swapnanildutta — APPROVED** [review]

**Pull request merged**
