### PR TITLE
 Added two Hackerrank programs 1. Designer Door Mat 2. String Split and Join

### PR DESCRIPTION
**Pull request by fharookshaik**
Hackerank Questions.

1. Designer Door mat

                      Mr. Vincent works in a door mat manufacturing company. One day, he designed a new door mat with the following 
                      specifications:

                    Mat size must be X. ( is an odd natural number, and  is  times .)
                    The design should have 'WELCOME' written in the center.
                    The design pattern should only use |, . and - characters.
                     Sample Designs

                              Size: 7 x 21 
                                   ---------.|.---------
                                    ------.|..|..|.------
                                      ---.|..|..|..|..|.---
                                -------WELCOME-------
                                      ---.|..|..|..|..|.---
                                    ------.|..|..|.------
                                  ---------.|.---------
    
                            Size: 11 x 33
                           ---------------.|.---------------
                             ------------.|..|..|.------------
                               ---------.|..|..|..|..|.---------
                                ------.|..|..|..|..|..|..|.------
                                 ---.|..|..|..|..|..|..|..|..|.---
                     -------------WELCOME-------------
                                 ---.|..|..|..|..|..|..|..|..|.---
                               ------.|..|..|..|..|..|..|.------
                             ---------.|..|..|..|..|.---------
                           ------------.|..|..|.------------
                         ---------------.|.---------------
                  Input Format

                      A single line containing the space separated values of  and .
                     Constraints

               Output Format

                           Output the design pattern.

                Sample Input

                                 9 27
              Sample Output

                      ------------.|.------------
                        ---------.|..|..|.---------
                          ------.|..|..|..|..|.------
                            ---.|..|..|..|..|..|..|.---
                  ----------WELCOME----------
                           ---.|..|..|..|..|..|..|.---
                         ------.|..|..|..|..|.------
                       ---------.|..|..|.---------
                     ------------.|.------------

2.String Split and Join

         In Python, a string can be split on a delimiter.

          Example:

            >>> a = "this is a string"
            >>> a = a.split(" ") # a is converted to a list of strings. 
            >>> print a
            ['this', 'is', 'a', 'string']
            Joining a string is simple:

            >>> a = "-".join(a)
            >>> print a
           this-is-a-string 
           Task
           You are given a string. Split the string on a " " (space) delimiter and join using a - hyphen.

            Input Format
            The first line contains a string consisting of space separated words.

           Output Format
           Print the formatted string as explained above.

          Sample Input

                                  this is a string   
                                  
          Sample Output

                                 this-is-a-string

Hi, 

I'm Shaik Fharook. I've added two more solved hacker rank programs under python folder 

Please find them and feel free to contact me if any problem occurs.

Thank You

### CODE REVIEW

**Comment by fharookshaik** [comment]
Looks like there's an error while creating a PR. And I see everyone is facing the same issue. Please resolve it soon @swapnanildutta

**Comment by fharookshaik** [comment]
The codes I've published are rechecked and working fine for all the test cases. I'm getting the PR error. Please resolve it @swapnanildutta .

**Comment by swapnanildutta** [comment]
That's not important, I'll check the PR and merge it. Thanks and keep contributing.

**Comment by fharookshaik** [comment]
Oh! Alright. Thanks  @swapnanildutta

**Review by swapnanildutta — CHANGES_REQUESTED** [review]
Please add the HackerRank Question on top as comment. Thank you.

**Comment by fharookshaik** [comment]
Hey @swapnanildutta  I've made changes as you requested. Please review them and report me if you need any other changes.

Thank You

**Comment by fharookshaik** [comment]
Hey @swapnanildutta . I've made all the changes that you've requested. Please approve my PR.

**Comment by swapnanildutta** [comment]
Where is the change?

**Comment by fharookshaik** [comment]
You've asked to add the names of the hacker-rank programs to the first comment and I've done that. Please check the title and the first comment and I'm attaching the screenshot as a reference. Feel free to comment on this issue and I'm ready to resolve them as soon as possible.

Thank You
Screenshot 2020-10-05 221156

**Comment by swapnanildutta** [comment]
I asked for the entire question as a comment in the file where the code is present.

**Comment by fharookshaik** [comment]
Oh! Got it. I'll post them in a minute. Please find them.

Thank You

**Comment by fharookshaik** [comment]
Added the questions. Review my PR.

Thank You

**Comment by swapnanildutta** [comment]
Please commit your changes.

**Comment by fharookshaik** [comment]
I've Committed.

**Comment by swapnanildutta** [comment]
Please check the other already existing codes before committing.

**Comment by fharookshaik** [comment]
okay got it. Some one else have committed one of the programs that i've written. No issues. I'll commit another PR, with the new one.
Does it sounds good?

**Comment by fharookshaik** [comment]
Commited bro.

**Comment by fharookshaik** [comment]
Looks like the labeler is giving an error every time. Is there anything that I've to concern about that?

**Review by swapnanildutta — APPROVED** [review]

**Comment by fharookshaik** [comment]
Hey, Thanks for accepting the PR. Add the 'hacktoberfest-accepted' label to the PR as it is mandatory as per new rules of hacktoberfest. 

Thank You.

**Pull request merged**
