### PR TITLE
Create LeftRotation.py

### PR DESCRIPTION
**Pull request by AthulJoseph27**

### CODE REVIEW

**Comment by AthulJoseph27** [comment]
How to pass the Labeler check

**Comment by AthulJoseph27** [comment]
How to pass the Labeler check?

**Comment by swapnanildutta** [comment]
> 
> 
> How to pass the Labeler check?

That's not necessary.

**Review by AthulJoseph27 — COMMENTED** [review]
Removed unused imports and added the name of the question on top of the file. Removed Extra whitespaces.

**Review by swapnanildutta — APPROVED** [review]

**Review by swapnanildutta — APPROVED** [review]

**Review by swapnanildutta — APPROVED** [review]

**Pull request merged**
